<!DOCTYPE HTML>

<HTML>

<HEAD>
	<META HTTP-EQUIV="CONTENT-TYPE"
		CONTENT="TEXT/HTML; CHARSET=UTF-8" />
        <LINK REL="STYLESHEET" TYPE="TEXT/CSS" HREF="COUNTER.CSS">
        <SCRIPT SRC="COUNTER.JS"></SCRIPT>
	
</HEAD>
	
<BODY>
<!-- GIVE A SUITABLE HEADING USING H1 TAG-->
		<H1>INCREMENT AND DECREMENT COUNTER</H1>

		<DIV CLASS="CONTAINER">			
		<!-- ADDING BUTTON AND HEADING TO SHOW THE DIGITS -->
		<!--INCREMENT() AND DECREMENT() FUNCTIONS ON BUTTON CLICK-->
			<BUTTON ONCLICK="INCREMENT()">+</BUTTON>
			<H2 ID="COUNTING"></H2>
			<BUTTON ONCLICK="DECREMENT()">-</BUTTON>		
		</DIV>

</BODY>

</HTML>

