apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'mysql'
        static_configs:
          - targets: ['mysql:3306']
            labels:
              app: mysql
      - job_name: 'nginx'
        static_configs:
          - targets: ['nginx:80']
            labels:
              app: nginx

