apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: fe
spec:
  selector:
    matchLabels:
      app: nginx
      app: mysql
  endpoints:
  - port: http
    path: /metrics
  endpoints:
  - port: mysql
    path: /metrics
